### ISSUE TITLE
UnboundLocalError: local variable 'search_results' referenced before assignment

### ISSUE THREAD

**Issue by apo86** [xbmc/metadata.themoviedb.org.python#108]
```
2021-10-19 21:25:35.008 T:2991     INFO <general>: [metadata.themoviedb.org.python]: Find movie with title 'Fabricated City' from year 'None'
2021-10-19 21:25:35.010 T:2991    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'search_results' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 185, in <module>
                                                       run()
                                                     File "/home/osmc/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 172, in run
                                                       search_for_movie(params["title"], params.get("year"), params['handle'], settings)
                                                     File "/home/osmc/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py", line 40, in search_for_movie
                                                       if not search_results:
                                                   UnboundLocalError: local variable 'search_results' referenced before assignment
                                                   -->End of Python script error report<--

2021-10-19 21:25:35.421 T:2991  WARNING <general>: CPythonInvoker(9, /home/osmc/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py): the python script "/home/osmc/.kodi/addons/metadata.themoviedb.org.python/python/scraper.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-10-19 21:25:35.421 T:2991     INFO <general>: Python interpreter stopped
2021-10-19 21:25:35.433 T:2979    ERROR <general>: GetDirectory - Error getting plugin://metadata.themoviedb.org.python/?action=find&pathSettings=%7b%22RatingS%22%3a%22TMDb%22%2c%22add_tags%22%3atrue%2c%22certprefix%22%3a%22Rated%20%22%2c%22enable_fanarttv_artwork%22%3afalse%2c%22fanart%22%3atrue%2c%22fanarttv_clientkey%22%3a%22%22%2c%22fanarttv_language%22%3a%22en%22%2c%22imdbanyway%22%3atrue%2c%22keeporiginaltitle%22%3afalse%2c%22landscape%22%3atrue%2c%22language%22%3a%22de-DE%22%2c%22lastUpdated%22%3a%220%22%2c%22multiple_studios%22%3atrue%2c%22originalUrl%22%3a%22%22%2c%22previewUrl%22%3a%22%22%2c%22searchlanguage%22%3a%22en-US%22%2c%22tmdbcertcountry%22%3a%22de%22%2c%22trailer%22%3afalse%2c%22traktanyway%22%3afalse%7d&title=Fabricated%20City

```

Pretty sure #101 is responsible for this.

**Comment by rmrector** [comment]
found it. Fix incoming.

**Comment by mkaflowski** [comment]
> So to be honest I don't know what the new search_lanugage parameter even does.

I have added search_languege because I wanted results in polish language but sorting in polish was kind of broken. For example if you have popular movie "My Son" it has polish tilte "Mój Syn" and some other small movie with name "My Son" was returned because it matched better to file name("My Son.mp4"). I will check if it is always "en-US" again next week.

**Comment by donnje** [comment]
I Have on W kodi 19 and I see the italian scrapes if I capy the file 
.kodi/userdata/Database/MyVideos.db and I  replace it with the file on android Kodi 19.2,  disable scrapes updating should i see italian scrapes or am i saying nonsense?

**Comment by apo86** [comment]
No, don't copy that file. You should provide a log, like KarellenX explained, and/or a more detailed description of your problem. What are you doing (step by step), what is the outcome you expect, what is the actual outcome? Also probably open a separate issue here or post to the Kodi forums, because it seems like a different problem.
From what you have said so far it sounds like you have problems with the language of the files being scraped. If that is the case, please have a look at my previous post and check the steps to change language settings for the scraper on your existing movie source(s).

**Comment by Peacekeeper2000** [comment]
> 
> @Peacekeeper2000 Go to Files -> open context menu of the source folder -> "Change content" -> "- Settings" -> "Search language". Exit all menus with "ok" or the change won't be saved.
> 
> PS: Unrelated, but if anyone is wondering (like me) where that information is stored, it's in .kodi/userdata/Database/MyVideos.db in the "path" table.

No Problem, I am waiting for 1.5.1 before I make a try with the search language again.
( And when I find the correct year, it currently works fine without changing the search language to de-DE. - Just when I put an additional `(NV)` in th efilename to mark that the movie is not complete, it struggles again - looking forward, if that will also happen in 1.5.1 )
